const $=id=>document.getElementById(id), STORE="heading-trainer-v1";
const saved=JSON.parse(localStorage.getItem(STORE)||"{}");
let state={mode:saved.mode||"math",correct:saved.correct||0,wrong:saved.wrong||0,streak:saved.streak||0,answered:false,q:null};
const norm=n=>((n-1)%360+360)%360+1;
const fmt=n=>String(norm(n)).padStart(3,"0");
const value=id=>{const raw=$(id)?.value.trim()||"";return /^(?:00[1-9]|0[1-9][0-9]|[12][0-9]{2}|3[0-5][0-9]|360)$/.test(raw)?Number(raw):null};
function save(){localStorage.setItem(STORE,JSON.stringify({...state,q:null,range:$("range").value,direction:$("direction").value}))}
function stats(){const t=state.correct+state.wrong;$("correct").textContent=state.correct;$("streak").textContent=state.streak;$("accuracy").textContent=t?Math.round(state.correct/t*100)+" %":"–"}
function setMode(m){state.mode=m;document.querySelectorAll(".tabs button").forEach(b=>b.classList.toggle("active",b.dataset.mode===m));$("mathSettings").classList.toggle("hidden",m!=="math");$("circuitSettings").classList.toggle("hidden",m!=="circuit");save();question()}
function heading(){return Math.floor(Math.random()*360)+1}
function delta(){const max=Number($("range").value), steps=[];for(let n=10;n<=max;n+=10)steps.push(n);return steps[Math.floor(Math.random()*steps.length)]}
function question(){state.answered=false;$("feedback").classList.add("hidden");$("form").classList.remove("hidden");$("mathQuestion").classList.toggle("hidden",state.mode!=="math");$("circuitQuestion").classList.toggle("hidden",state.mode!=="circuit");$("directionBadge").classList.toggle("hidden",state.mode!=="circuit");
 if(state.mode==="math"){const start=heading(),d=delta(),sign=Math.random()<.5?1:-1;state.q={start,d,sign,answer:norm(start+sign*d)};$("questionType").textContent="VYPOČÍTEJ HEADING";$("mathQuestion").textContent=`${fmt(start)}° ${sign>0?"+":"−"} ${fmt(d)}°`;$("instruction").textContent="Odpověď zadej trojmístně v rozsahu 001–360";$("inputs").innerHTML='<div class="answergrid single"><label>Výsledný heading<input id="answer" inputmode="numeric" maxlength="3" placeholder="000"></label></div>';}
 else{const runway=Math.floor(Math.random()*36)+1,hdg=runway===36?360:runway*10,setting=$("direction").value,dir=setting==="mixed"?(Math.random()<.5?"right":"left"):setting,s=dir==="right"?1:-1;state.q={runway,hdg,dir,cross:norm(hdg+s*90),down:norm(hdg+180),base:norm(hdg-s*90)};$("questionType").textContent="DOPLŇ HEADINGY OKRUHU";$("runway").textContent=String(runway).padStart(2,"0");$("directionBadge").textContent=dir==="right"?"PRAVÝ OKRUH":"LEVÝ OKRUH";$("instruction").textContent="Zadej heading po 1. zatáčce, po 2. zatáčce a na base leg";$("inputs").innerHTML='<div class="answergrid"><label>1. zatáčka<input id="cross" inputmode="numeric" maxlength="3" placeholder="000"></label><label>Downwind<input id="down" inputmode="numeric" maxlength="3" placeholder="000"></label><label>Base leg<input id="base" inputmode="numeric" maxlength="3" placeholder="000"></label></div>';}
 setTimeout(()=>$("inputs").querySelector("input")?.focus(),0)}
function check(force=false){if(state.answered)return;const q=state.q,a=value("answer"),c=value("cross"),d=value("down"),b=value("base");const right=!force&&(state.mode==="math"?a===q.answer:c===q.cross&&d===q.down&&b===q.base);state.answered=true;if(right){state.correct++;state.streak++}else{state.wrong++;state.streak=0}$("form").classList.add("hidden");$("feedback").classList.remove("hidden");$("feedback").className="feedback "+(right?"good":"bad");$("feedbackTitle").textContent=right?"✓ Správně":"✕ Tentokrát ne";$("solution").innerHTML=state.mode==="math"?`<div class="result">${fmt(q.answer)}°</div>`:`<div class="legs"><div><small>1. ZATÁČKA</small><strong>${fmt(q.cross)}°</strong></div><div><small>DOWNWIND</small><strong>${fmt(q.down)}°</strong></div><div><small>BASE LEG</small><strong>${fmt(q.base)}°</strong></div></div>`;stats();save();$("next").focus()}
document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$("form").onsubmit=e=>{e.preventDefault();check()};$("dontKnow").onclick=()=>check(true);$("next").onclick=question;$("settingsBtn").onclick=()=>$("settings").classList.toggle("closed");[$("range"),$("direction")].forEach(x=>x.onchange=()=>{save();question()});$("reset").onclick=()=>{if(confirm("Opravdu vynulovat statistiky?")){state.correct=state.wrong=state.streak=0;stats();save()}};document.addEventListener("keydown",e=>{if(e.key==="Enter"&&state.answered){e.preventDefault();question()}});$("range").value=saved.range||"180";$("direction").value=saved.direction||"mixed";stats();setMode(state.mode);if("serviceWorker" in navigator)navigator.serviceWorker.register("service-worker.js");
